<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'UserVoice\Module'              => __DIR__ . '/Module.php',
  'UserVoice\Listener\UVListener' => __DIR__ . '/src/UserVoice/Listener/UVListener.php',
);
