<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("Daily.IO")->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath() . '/vendors/fullcalendar/fullcalendar.css')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-responsive.min.css')
                        ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/assets/styles.css')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css') ?>
        
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <script src="/vendors/jquery-1.9.1.min.js"></script>
        <script src="/vendors/jquery-ui-1.10.3.custom.min.js"></script>
        
    </head>
    <body>
         <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Daily.IO</a>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Daily.IO - <?php echo date('Y') ?></p>
            </footer>
        </div> <!-- /container -->
        
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/assets/scripts.js')
        							  ->prependFile($this->basePath() . '/vendors/bootstrap-wysiwyg.js')
        							  ->prependFile($this->basePath() . '/vendors/jquery.hotkeys.js')
        							  //->prependFile($this->basePath() . '/vendors/fullcalendar/gcal.js')
        							  ->prependFile($this->basePath() . '/vendors/fullcalendar/fullcalendar.js')
                                      ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js') ?>
        
        <?php echo $this->inlineScript() ?>

        <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
    </body>
</html>
