<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("Daily.IO")->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        // ->prependStylesheet($this->basePath() . '/assets/app.css?20140203')
                        //->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-responsive.min.css')
                        ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
                        // ->prependStylesheet($this->basePath() . '/assets/styles.css')
                        ->prependStylesheet($this->basePath() . '/assets/application.css?123')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/datepicker.css')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css') 

                        ?>
        
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <script src="/vendors/jquery-1.9.1.min.js"></script>
        <script src="/vendors/jquery-ui-1.10.3.custom.min.js"></script>

        <script src="/assets/scripts.js"></script>

    </head>
    <body>
         <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">

                    <?php if($this->placeholder('page_name')!= "") { ?>

                    <?php if(false && $this->placeholder('page_hash')!= "" && $this->placeholder('prev_date')!= "") { ?>
                    <a tabindex="-1" id="previous-dailyio" class="tooltip-bottom" data-original-title="Previous Daily.IO" href="/todo/<?php echo $this->placeholder('page_hash'); ?>/<?php echo $this->placeholder('prev_date'); ?>"><i class="icon-chevron-left"></i></a>
                    <?php } ?>

                    <?php if($this->placeholder('page_hash')!= "" && $this->placeholder('actual_date')!= "") { ?>
                    <a tabindex="-1" data-page-hash="<?php echo $this->placeholder('page_hash'); ?>" data-date="<?php echo $this->placeholder('actual_date'); ?>" id="dailyio-datepicker" href="javascript:"><i class="fa fa-calendar"></i></a>
                    <?php } ?>

                    <ul class="nav pull-right">
                        <li class="dropdown">

                            <a style="background-color: #E5E5E5;
    box-shadow: 0 3px 8px rgba(0, 0, 0, 0.125) inset;" id="bookmark" role="button" class="dropdown-toggle" data-toggle="dropdown">
                                <b><?php echo $this->placeholder('page_name'); ?>'s Dailys</b>
                            </a>
                            
                            <ul class="dropdown-menu">
                                <?php if($this->placeholder('page_hash')!= "") { ?>
                                <li>
                                    <a tabindex="-1" href="/todo/<?php echo $this->placeholder('page_hash'); ?>"> My DailyIO</a>
                                </li>
                                <li>
                                    <a tabindex="-1" href="/week/<?php echo $this->placeholder('page_hash'); ?>">My Week</a>
                                </li>
                                <?php } ?>
                                <?php if($this->placeholder('team')!= "") { ?>
                                <li>
                                    <a tabindex="-1" href="/team/<?php echo $this->placeholder('team'); ?>">My Team</a>
                                </li>
                                <?php } ?>
                                <?php if($this->placeholder('user_page_hash')!= "" && $this->placeholder('user_page_name')!= "") { ?>
                                <li>
                                    <a tabindex="-1" href="/todo/<?php echo $this->placeholder('user_page_hash'); ?>"> <?php echo $this->placeholder('user_page_name'); ?>'s DailyIO</a>
                                </li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>
                    <?php } ?>
                    <?php if($this->placeholder('page_hash')!= "") { ?>
                    <a class="brand" href="/todo/<?php echo $this->placeholder('page_hash'); ?>">Daily.IO</a>
                    <?php } else { ?>
                    <a class="brand" href="/">Daily.IO</a>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
        <div id="main-content" class="container-fluid">
            <?php echo $this->content; ?>
            
        </div> <!-- /container -->
        
        <footer class="navbar-fixed-bottom">
            <div class="navbar-inner">
            <p style="float:left"><!--by <a href="http://twitter.com/jorgesierra">@jorgesierra</a> - --><?php echo date('Y') ?></p>
            <p style="float:right;">Inspired by <a style="color: #006DCC" href="http://todomvc.com">todomvc.com</a></p>
            <div class="clearfix"></div>
            </div>
        </footer>
        <!-- Scripts -->
        <?php echo $this->headScript()//->prependFile($this->basePath() . '/assets/scripts.js')
                                      ->prependFile($this->basePath() . '/assets/masonry.pkgd.min.js')
                                      ->prependFile($this->basePath() . '/bootstrap/js/bootstrap-datepicker.js')
                                      ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js') ?>
        
        <?php echo $this->inlineScript() ?>

        
    </body>
</html>
