<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("Daily.IO")->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/app.css')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-responsive.min.css')
                        ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/assets/styles.css')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css') ?>
        
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <script src="/vendors/jquery-1.9.1.min.js"></script>
        <script src="/vendors/jquery-ui-1.10.3.custom.min.js"></script>
        
    </head>
    <body>
         <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <!-- <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                    </a> -->
                    <a class="brand" href="/">Daily.IO</a>

                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">

                                <a id="bookmark" data-toggle="dropdown" href="/todo/<?php echo $this->placeholder('page_hash'); ?>">
                                    <b><?php echo $this->placeholder('page_name'); ?>'s Daily.IO</b>
                                </a>
                                
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        <div class="container-fluid">
            <?php echo $this->content; ?>
            
        </div> <!-- /container -->
        
        <footer class="navbar-fixed-bottom">
            <div class="navbar-inner">
            <p style="float:left"><a href="www.case-inc.com">www.case-inc.com</a> - <?php echo date('Y') ?></p>
            <p style="float:right">Inspired by <a href="todomvc.com">todomvc.com</a></p>
            <div class="clearfix"></div>
            </div>
        </footer>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/assets/scripts.js')
                                      ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js') ?>
        
        <?php echo $this->inlineScript() ?>

        <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
    </body>
</html>
