<div class="row-fluid">
	<div class="span12" id="content">
		<section id="dailyInit">
			<header id="header">
				<h1>Create your Daily.IO page</h1>
			</header>
			<section>
				<form id="createDailyIOForm"><input name="name" id="new-todo" placeholder="Enter your name" autofocus autocomplete="off"></form>
				<a id="submitCreatePageForm" class="btn btn-large btn-block btn-primary" href="javascript:">Submit</a>
			</section>
		</section>		
	</div>
</div>

<script>
formSubmitted = false;
$(document).on("submit", "#createDailyIOForm", function(event) {
	if(formSubmitted === false) {
		$('#submitCreatePageForm').addClass('disabled').html("Please wait...");
    	nameInput = $('#new-todo');
    	if(jQuery.trim(nameInput.val()) == '') {
    		nameInput.focus();
    		formSubmitted = false;
    	} else {
    		formSubmitted = true;
    		$.ajax({
    			url: "/page",
    			type: "post",
    	        data: {"name":nameInput.val()},
    			success: function(jsonData) {
        			//console.log(jsonData);
    				$('#submitCreatePageForm').addClass('disabled').html("Redirecting to your page");
    				window.location.replace("/todo/"+jsonData.data.page_hash);
    			}
    		});
    	}
	}
	return false;
});

$(document).on("click", "#submitCreatePageForm", function(event){
    $('#createDailyIOForm').submit();
});
</script>